#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: build toolchain

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build ToolChain"
        required: true
        default: "build"
  # release:
  #   types: [published]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  #  schedule:
  #    - cron: 0 8 * * 5
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
          token: ${{ secrets.R_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod \
          cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Clone source code
        run: |
          git clone -b chongshengB --depth=1 https://github.com/Yh793/rt-n56u.git /opt/rt-n56u
      - name: build toolchain
        run: |
          cd /opt/rt-n56u/toolchain-mipsel
          ./clean_toolchain
          ./build_toolchain
          mkdir -p /opt/images/
          cd /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x
          tar -Jcf /opt/images/mipsel-linux-uclibc.tar.xz ./
      - name: Organize files
        id: organize
        run: |
          echo "###########################"
          echo "###########################"
          echo "###########################"
          echo "::set-output name=status::success"
      - name: Upload packages - push to artifact file
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success'
        with:
          name: Padavan-packages
          path: /opt/images
      - name: Update README.md
        run: |
          git pull origin master
          sudo mv -f /opt/images/mipsel-linux-uclibc.tar.xz ./
          git config user.name  Robot
          git config user.email github-actions@github.com
          git add .
          git commit -m "update toolchain" -a
          git push
      - name: Remove obsolete firmwares on artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        if: always()
        with:
          age: '3 day'
          skip-recent: 5
