name: build toolchain

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build ToolChain"
        required: true
        default: "build"
  # release:
  #   types: [published]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  #  schedule:
  #    - cron: 0 8 * * 5
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
          token: ${{ secrets.R_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Clone source code
        run: |
          git clone -b chongshengB --depth=1 https://github.com/Yh793/rt-n56u.git /opt/rt-n56u
      - name: build toolchain
        run: |
          cd /opt/rt-n56u/toolchain-mipsel
          ./clean_toolchain
          ./build_toolchain
          mkdir -p /opt/images/
          cd /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x
          tar -Jcf /opt/images/mipsel-linux-uclibc.tar.xz *
          echo "BUILDDONE=success" >> $GITHUB_ENV
      - name: Update README.md
        if: env.BUILDDONE == 'success'
        run: |
          git pull origin master
          sudo mv -f /opt/images/mipsel-linux-uclibc.tar.xz ./
          git config user.name  Robot
          git config user.email github-actions@github.com
          git add .
          git commit -m "update toolchain" -a
          git push
      - name: Remove obsolete firmwares on artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        if: always()
        with:
          age: '3 day'
          skip-recent: 5
